//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkManager.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        MarkManager.ServiceReference.CompositeType GetDataUsingDataContract(MarkManager.ServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MarkManager.ServiceReference.CompositeType> GetDataUsingDataContractAsync(MarkManager.ServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        int Login(string username, string password, short type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string username, string password, short type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClazzs", ReplyAction="http://tempuri.org/IService/GetClazzsResponse")]
        Model.Clazz[] GetClazzs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClazzs", ReplyAction="http://tempuri.org/IService/GetClazzsResponse")]
        System.Threading.Tasks.Task<Model.Clazz[]> GetClazzsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateClazz", ReplyAction="http://tempuri.org/IService/UpdateClazzResponse")]
        int UpdateClazz(Model.Clazz clazz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateClazz", ReplyAction="http://tempuri.org/IService/UpdateClazzResponse")]
        System.Threading.Tasks.Task<int> UpdateClazzAsync(Model.Clazz clazz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClazz", ReplyAction="http://tempuri.org/IService/DeleteClazzResponse")]
        int DeleteClazz(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteClazz", ReplyAction="http://tempuri.org/IService/DeleteClazzResponse")]
        System.Threading.Tasks.Task<int> DeleteClazzAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindClazz", ReplyAction="http://tempuri.org/IService/FindClazzResponse")]
        Model.Clazz[] FindClazz(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FindClazz", ReplyAction="http://tempuri.org/IService/FindClazzResponse")]
        System.Threading.Tasks.Task<Model.Clazz[]> FindClazzAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MarkManager.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MarkManager.ServiceReference.IService>, MarkManager.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MarkManager.ServiceReference.CompositeType GetDataUsingDataContract(MarkManager.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MarkManager.ServiceReference.CompositeType> GetDataUsingDataContractAsync(MarkManager.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int Login(string username, string password, short type) {
            return base.Channel.Login(username, password, type);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string username, string password, short type) {
            return base.Channel.LoginAsync(username, password, type);
        }
        
        public Model.Clazz[] GetClazzs() {
            return base.Channel.GetClazzs();
        }
        
        public System.Threading.Tasks.Task<Model.Clazz[]> GetClazzsAsync() {
            return base.Channel.GetClazzsAsync();
        }
        
        public int UpdateClazz(Model.Clazz clazz) {
            return base.Channel.UpdateClazz(clazz);
        }
        
        public System.Threading.Tasks.Task<int> UpdateClazzAsync(Model.Clazz clazz) {
            return base.Channel.UpdateClazzAsync(clazz);
        }
        
        public int DeleteClazz(int id) {
            return base.Channel.DeleteClazz(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteClazzAsync(int id) {
            return base.Channel.DeleteClazzAsync(id);
        }
        
        public Model.Clazz[] FindClazz(string name) {
            return base.Channel.FindClazz(name);
        }
        
        public System.Threading.Tasks.Task<Model.Clazz[]> FindClazzAsync(string name) {
            return base.Channel.FindClazzAsync(name);
        }
    }
}
